name: Build, test and deliver container

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    name: Java 17 build, test, deliver container
    steps:
      - name: Check out repository
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17.0.2

      ## SONARCLOUD
      - name: Build and package project
        run: mvn -B verify

      # --- DOCKER --- #
      ### docker buildx ###
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      ### Docker login ###
      - name: Docker Hub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USER }}/utopia_edgeservice:latest .

      - name: Upload container to Docker Hub with Push
        run: docker push ${{ secrets.DOCKER_USER }}/utopia_edgeservice:latest
